services:
  logv2_app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    container_name: logv2_app 
    restart: always
    tty: true
    working_dir: /var/www/
    volumes:
      - ./app:/var/www
      - /var/www/tmp 
    networks:
      - log_net_v2 

  logv2_db:
    build:
      context: ./pgsql
      dockerfile: Dockerfile
      args:
        DB_VERSION_PG_SQL: ${DB_VERSION_PG_SQL}
    restart: always
    container_name: logv2_db
    tty: true
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - log_net_v2 


  #Nginx Service
  logv2_web:
    image: nginx:alpine
    container_name: logv2_webserver 
    restart: always
    tty: true
    ports:
      - "${NGINX_PORT}:80"
      # - "5443:443"
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/logs/:/var/log/nginx
    networks:
      - log_net_v2 

  #ADMINER
  logv2_adm:
    image: ${ADMINER_VERSION}
    container_name: logv2_adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - log_net_v2

  # logv2_zookeeper:
  #   container_name: logv2_zookeeper
  #   image: confluentinc/cp-zookeeper:7.3.2
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #
  # logv2_kafka:
  #   container_name: logv2_kafka
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - logv2_zookeeper
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


networks:
  log_net_v2:
    driver: bridge
